= "Egg-and-Bacon" breakfast: group commitments
Carlos Sanchez <carlos.sanchez@ubirch.com>
v0.0.1, 2021-11
:doctype: article
:encoding: utf-8
:lang: en
:xrefstyle: short
:numbered!:

[.normal]

== Together

Intelligent people are not the secret ingredient to making intelligent organizations. An intelligent organization is not the same as a collection of intelligent people working together. An intelligent person has different rules when working alone than when part of an organization. Realizing that the nature of an organization is different changes the perspective on the important elements to assemble a successful organization. I think that one of the key factors in an organization is the fact that the organization facilitates a good flow of information. Being able to communicate the purpose of the organization makes a lot of difference, it is a matter of communicating fast, and accurate, and targeted enough. The information should be available for everyone, but not everyone should hear/know everything. Another meaningful aspect is commitment, the point at which people are only involved but not committed. Being committed means that the person sees the goal of the organization as relevant and interesting. The person sees them as part of their personal development. Contrary to commitment is involvement, which represents a weak participation of the person in the realization of the purpose of the organization. All this doesn't mean that the person should not be knowledgeable of their domain, it means that it is not necessary that they be the best or the most intelligent in their domain. A third factor is responsibility. I believe that members of the organization should have their responsibilities well-defined, in other words, their roles. It is decisive that the person takes their participation in the organization seriously, and if their responsibilities are not clear enough, there could be a chance that tasks or important endeavors get diffused, and not acted upon.

_Flow of information:_

There are three pieces of information that present themselves as the most relevant in an organization. The first one is about the purpose of the organization. The second one is about the specific role or description of the tasks that a member should have. And last but not least, the third one is a clear message about how the members of the organization can enhance their abilities. The purpose of an organization is one of the most fundamental pillars of stability, the organization has to have a purpose, a destination, even if it is not clear if such will be the final one. This message has to permeate all corners of the organization, and every member should understand it and most importantly share it. It is very important to try and remove noise and double signals. Noise and double signals add extra layers of complexity that reduce productivity as the member will have to spend their time resolving the real purpose. Moreover, the role of the member should be well-defined and a description of their tasks and activities should be ready and clear, specially to new members. Roles play a significant part in the overall success of the organization, even if there are similar ones, just like in soccer, or other similar games, which have a clear strategy of the positions and objectives of each member. Note that roles can be temporal, depending on the ongoing strategy of the organization. One or more members can have the same role. That's fine, as long as it is clear what our strategy is during a current phase or pivot of the organization. Every respiration of an organization should aim at improvement or stability, which means that their members have to perform their roles in a better manner every time, sometimes doing something better requires practice and study, and the organization should provide a platform of constant training, which can be used by every member of the organization as a vector of self-improvement in the abilities or roles every member has.

_Commitment:_

When we are working in an organization and not everybody feels committed or responsible and only a few do the heavy work, it can be an unfair situation and can make that the organization's controls don't work, and slowly make the commitment strength to be reduced if not tuned up. Of course, levels of heavy doing can come in intervals to different people in the organization, depending on the current short-term goal, but if during some time, we notice that not everybody is committed and some dodge responsibilities or don't take them 100% seriously, it should a clear indication that there is something in the organization's dynamics that need attention. At this point, we should measure the commitment level of the overall organization, and observe what spots could get more participation or engagement.

_Responsibility:_

One of the greatest challenges in organization is to make everybody to participate, especially, when there are other peers around us. When we think that somebody else could do the current tasks, and therefore we don't participate, makes that a possible situation where nobody is willing to take the responsibility of the task. I believe that one of the key factors to increase responsibility and reduce these moments of diffusion is to have clear roles and clear tasks for all participants. Every one of us should know our roles and the areas with which we should be super active in the organization. The tasks of every role should be clear, and/or the assignations to these tasks should be explicit. Another way to increase people's participation is to directly ask for their input. However, from my point of view, recognizing a role, their tasks, and including everybody in the conversation can help increase the sense of responsibility and trust in the organization.
